#!/usr/bin/env bash

set -euo pipefail

workspace_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$workspace_dir/.env.local"
output_file="${1:-/tmp/assembler-supabase-import-$(date +%Y%m%d-%H%M%S).sql}"

read_env_value() {
	local key="$1"
	local line

	line="$(rg -m 1 "^${key}=" "$env_file" || true)"
	if [[ -z "$line" ]]; then
		echo "Local Supabase dump failed: required ${key}= value is missing from ${env_file}." >&2
		exit 1
	fi

	printf '%s' "${line#*=}"
}

if [[ ! -f "$env_file" ]]; then
	echo "Local Supabase dump failed: expected configuration file ${env_file} was not found." >&2
	exit 1
fi

hosted_user_id="$(read_env_value HOSTED_USER_ID)"
hosted_user_email="$(read_env_value HOSTED_EMAIL)"

if [[ ! "$hosted_user_id" =~ ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ ]]; then
	echo "Local Supabase dump failed: HOSTED_USER_ID must be the UUID of the hosted Supabase Auth user; received \"${hosted_user_id}\"." >&2
	exit 1
fi

if [[ -z "$hosted_user_email" ]]; then
	echo "Local Supabase dump failed: HOSTED_EMAIL must be the email address of that hosted Auth user." >&2
	exit 1
fi

temporary_file="${output_file}.tmp"
mkdir -p "$(dirname "$output_file")"

metadata_query="select format(
  \$sql\$insert into public.model_metadata (model_id, metadata, updated_at) values (%L, %L::jsonb, %L::timestamptz) on conflict (model_id) do update set metadata = excluded.metadata, updated_at = excluded.updated_at;\$sql\$,
  model_id,
  metadata::text,
  updated_at::text
) from public.model_metadata order by model_id;"

projects_query="select format(
  \$sql\$insert into public.projects (id, user_id, user_email, name, graph_document, created_at, updated_at) values (%L::uuid, %L::uuid, %L, %L, %L::jsonb, %L::timestamptz, %L::timestamptz) on conflict (id) do update set user_id = excluded.user_id, user_email = excluded.user_email, name = excluded.name, graph_document = excluded.graph_document, created_at = excluded.created_at, updated_at = excluded.updated_at;\$sql\$,
  id::text,
  :'hosted_user_id',
  :'hosted_user_email',
  name,
  graph_document::text,
  created_at::text,
  updated_at::text
) from public.projects order by created_at, id;"

{
	echo '-- Generated by scripts/dump-local-supabase.sh. Do not commit this file.'
	echo '-- Import this entire file in the SQL Editor of the intended hosted Supabase project.'
	echo 'begin;'
	printf '%s\n' "$metadata_query" | docker compose exec -T db psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -P pager=off -At
	printf '%s\n' "$projects_query" | docker compose exec -T db psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -v hosted_user_id="$hosted_user_id" -v hosted_user_email="$hosted_user_email" -P pager=off -At
	echo 'commit;'
} > "$temporary_file"

mv "$temporary_file" "$output_file"
echo "Local Supabase dump created: ${output_file}"
echo "Projects are assigned to hosted user ${hosted_user_email} (${hosted_user_id})."
